FACTIONS = {
	"The Arborec" : {
		"red": 0,
		"yellow" : 2,
		"green" : 10,
		"blue" : 0,
		"purple" : 0,
		"black" : 4,
		"orange" : 1,
		"pink" : 0,
	},
	"The Argent Flight" : {
		"red": 0,
		"yellow" : 2,
		"green" : 5,
		"blue" : 3,
		"purple" : 0,
		"black" : 0,
		"orange" : 6,
		"pink" : 1,
	},
	"The Barony of Letnev" : {
		"red": 5,
		"yellow" : 0,
		"green" : 0,
		"blue" : 3,
		"purple" : 4,
		"black" : 5,
		"orange" : 0,
		"pink" : 0,
	},
	"The Clan of Saar" : {
		"red": 0,
		"yellow" : 5,
		"green" : 4,
		"blue" : 0,
		"purple" : 0,
		"black" : 4,
		"orange" : 4,
		"pink" : 0,
	},
	"The Embers of Muaat" : {
		"red": 9,
		"yellow" : 2,
		"green" : 0,
		"blue" : 0,
		"purple" : 0,
		"black" : 0,
		"orange" : 5,
		"pink" : 1,
	},
	"The Emirates of Hacan" : {
		"red": 1,
		"yellow" : 9,
		"green" : 0,
		"blue" : 0,
		"purple" : 0,
		"black" : 0,
		"orange" : 7,
		"pink" : 0,
	},
	"The Empyrean" : {
		"red": 1,
		"yellow" : 0,
		"green" : 0,
		"blue" : 2,
		"purple" : 6,
		"black" : 7,
		"orange" : 0,
		"pink" : 2,
	},
	"The Federation of Sol" : {
		"red": 0,
		"yellow" : 5,
		"green" : 6,
		"blue" : 6,
		"purple" : 0,
		"black" : 0,
		"orange" : 0,
		"pink" : 0,
	},
	"The Ghosts of Creuss" : {
		"red": 0,
		"yellow" : 0,
		"green" : 0,
		"blue" : 11,
		"purple" : 1,
		"black" : 2,
		"orange" : 0,
		"pink" : 3,
	},
	"The L1Z1X Mindnet" : {
		"red": 4,
		"yellow" : 0,
		"green" : 0,
		"blue" : 4,
		"purple" : 4,
		"black" : 5,
		"orange" : 0,
		"pink" : 0,
	},
	"The Mahact Gene Sorcerers" : {
		"red": 1,
		"yellow" : 9,
		"green" : 0,
		"blue" : 0,
		"purple" : 3,
		"black" : 0,
		"orange" : 1,
		"pink" : 3,
	},
	"The Mentak Coalition" : {
		"red": 0,
		"yellow" : 3,
		"green" : 1,
		"blue" : 0,
		"purple" : 2,
		"black" : 5,
		"orange" : 5,
		"pink" : 1,
	},
	"The Naalu Collective" : {
		"red": 0,
		"yellow" : 5,
		"green" : 3,
		"blue" : 0,
		"purple" : 1,
		"black" : 3,
		"orange" : 4,
		"pink" : 1,
	},
	"The Naaz-Rokha Alliance" : {
		"red": 0,
		"yellow" : 5,
		"green" : 9,
		"blue" : 1,
		"purple" : 0,
		"black" : 1,
		"orange" : 1,
		"pink" : 0,
	},
	"The Nekro Virus" : {
		"red": 9,
		"yellow" : 0,
		"green" : 0,
		"blue" : 1,
		"purple" : 0,
		"black" : 6,
		"orange" : 1,
		"pink" : 0,
	},
	"The Nomad" : {
		"red": 0,
		"yellow" : 0,
		"green" : 1,
		"blue" : 7,
		"purple" : 4,
		"black" : 3,
		"orange" : 0,
		"pink" : 2,
	},
	"Sardakk Norr" : {
		"red": 8,
		"yellow" : 1,
		"green" : 2,
		"blue" : 0,
		"purple" : 0,
		"black" : 5,
		"orange" : 1,
		"pink" : 0,
	},
	"The Titans of Ul" : {
		"red": 0,
		"yellow" : 0,
		"green" : 1,
		"blue" : 1,
		"purple" : 5,
		"black" : 0,
		"orange" : 0,
		"pink" : 10,
	},
	"The Universities of Jol-Nar" : {
		"red": 0,
		"yellow" : 0,
		"green" : 3,
		"blue" : 7,
		"purple" : 7,
		"black" : 0,
		"orange" : 0,
		"pink" : 0,
	},
	"The Vuil'Raith Cabal" : {
		"red": 6,
		"yellow" : 0,
		"green" : 1,
		"blue" : 0,
		"purple" : 0,
		"black" : 6,
		"orange" : 4,
		"pink" : 0,
	},
	"The Winnu" : {
		"red": 0,
		"yellow" : 2,
		"green" : 0,
		"blue" : 0,
		"purple" : 6,
		"black" : 1,
		"orange" : 0,
		"pink" : 8,
	},
	"The Xxcha Kingdom" : {
		"red": 0,
		"yellow" : 3,
		"green" : 6,
		"blue" : 6,
		"purple" : 2,
		"black" : 0,
		"orange" : 0,
		"pink" : 0,
	},
	"The Yin Brotherhood" : {
		"red": 0,
		"yellow" : 1,
		"green" : 0,
		"blue" : 1,
		"purple" : 8,
		"black" : 5,
		"orange" : 0,
		"pink" : 2,
	},
	"The Yssaril Tribes" : {
		"red": 0,
		"yellow" : 5,
		"green" : 6,
		"blue" : 1,
		"purple" : 0,
		"black" : 5,
		"orange" : 0,
		"pink" : 0,
	}
}